# Generated by Django 3.2.10 on 2023-11-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emfood', '0002_emfood_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emfood',
            name='limit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
