# Generated by Django 3.2.10 on 2023-11-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emfood', '0003_emfood_limit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emfood',
            name='shere',
            field=models.BooleanField(default=False),
        ),
    ]
